feat: 测试自动部署2

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -22,9 +22,11 @@ jobs:
 
       - name: 测试 SSH 连接
         run: |
-          for IP in ${{ secrets.SSH_SERVER_IP_CONFIG }} ${{ secrets.SSH_SERVER_IP_DISCORD }} ${{ secrets.SSH_SERVER_IP_QQ_BOT }}  ${{ secrets.SSH_SERVER_IP_QQ }}; do
-            echo "Testing SSH connection to $IP..."
-            ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER_USER }}@$IP "echo 'SSH connection to $IP successful!' || echo 'Connection failed for $IP'"
+          count=1
+          for IP in ${{ secrets.SSH_SERVER_IP_CONFIG }} ${{ secrets.SSH_SERVER_IP_DISCORD }} ${{ secrets.SSH_SERVER_IP_QQ_BOT }} ${{ secrets.SSH_SERVER_IP_QQ }}; do
+            echo "Testing SSH connection to IP $count..."
+            ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER_USER }}@$IP "echo 'SSH connection to $count successful!' || echo 'Connection failed for $count'"
+            count=$((count + 1))
           done
 
       - name: 安装 rsync
